name: qc-backtest-coordinator
channels:
  - conda-forge
  - defaults
dependencies:
  - conda
  - python=3.8
  - pandas
  - numpy
  - python-dateutil
  - babel
  - scikit-learn
  - dictdiffer
  - backoff
  - ratelimit
  - ratelimiter
  - coolname
  - ciso8601
  - requests